# Generated by Django 5.0.6 on 2024-09-14 11:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
