# Generated by Django 5.0.6 on 2024-06-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0002_alter_video_hls_playlist_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_playlist_files',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='original_video',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
