# Generated by Django 5.0.6 on 2024-06-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0003_video_hls_playlist_files_video_original_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='hls_playlist',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='hls_playlist_files',
            field=models.FileField(blank=True, default='', upload_to='hls/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='original_video',
            field=models.FileField(blank=True, default='', upload_to='original_videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
        ),
    ]
