# Generated by Django 5.0.6 on 2024-06-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0005_alter_video_created_at_alter_video_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hls_playlist_files',
        ),
        migrations.RemoveField(
            model_name='video',
            name='original_video',
        ),
        migrations.AlterField(
            model_name='video',
            name='hls_playlist',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
