# Generated by Django 5.0.6 on 2024-06-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0007_alter_video_hls_playlist_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
