# Generated by Django 5.0.6 on 2024-06-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0009_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='hls_playlist',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
