# Generated by Django 5.0.6 on 2024-07-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0011_alter_video_created_at_alter_video_hls_playlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
