# Generated by Django 5.0.6 on 2024-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0013_video_age_video_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('serie', 'serie'), ('film', 'film')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='resolution',
            field=models.CharField(blank=True, choices=[('HD', 'HD'), ('4K', '4K')], max_length=20, null=True),
        ),
    ]
