# Generated by Django 5.0.6 on 2024-09-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0015_alter_video_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='release_date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
