# Generated by Django 5.0.6 on 2024-09-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0016_alter_video_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='age',
            field=models.CharField(blank=True, choices=[('0', 'Ohne Altersbeschränkung'), ('6', 'Ab 6 Jahren'), ('12', 'Ab 12 Jahren'), ('16', 'Ab 16 Jahren'), ('18', 'Ab 18 Jahren')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='release_date',
            field=models.CharField(blank=True, choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=4, null=True),
        ),
    ]
