# Generated by Django 5.0.6 on 2024-10-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0017_alter_video_age_alter_video_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
