# Generated by Django 5.0.6 on 2024-10-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0019_videoconversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoConversion',
        ),
    ]
